/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package art_gallery;
import java.util.ArrayList;
import java.util.Iterator;
import model.Category;
import model.Artist;
import dao.CategoryDao;
import dao.ArtistDao;

/**
 *
 * @author This Pc
 */
public class AddNewArtist1 extends javax.swing.JFrame {

    /**
     * Creates new form AddNewArt
     */
    public AddNewArtist1() {
        initComponents();
        jButton_save.setEnabled(false);
    }
    
    public void validateFields(){
    String artist_name= jTextField_artistname.getText();
    String art_name=jTextField_artname.getText();
    if(!artist_name.equals("") && !art_name.equals(""))
        jButton_save.setEnabled(true);
    else
        jButton_save.setEnabled(false);
        
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel_heading = new javax.swing.JLabel();
        jLabel_artistname = new javax.swing.JLabel();
        jTextField_artistname = new javax.swing.JTextField();
        jLabel_category2 = new javax.swing.JLabel();
        jComboBox_category2 = new javax.swing.JComboBox<>();
        jLabel_artname = new javax.swing.JLabel();
        jTextField_artname = new javax.swing.JTextField();
        jButton_save = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jButton_close1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/small-page-background.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 134));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_heading.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_heading.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_heading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        jLabel_heading.setText("Artist Information");
        getContentPane().add(jLabel_heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 16, 220, 25));

        jLabel_artistname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_artistname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_artistname.setText("Artist Name:");
        getContentPane().add(jLabel_artistname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 110, -1));

        jTextField_artistname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField_artistname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_artistnameActionPerformed(evt);
            }
        });
        jTextField_artistname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_artistnameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_artistname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 270, 30));

        jLabel_category2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_category2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_category2.setText("Category:");
        getContentPane().add(jLabel_category2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jComboBox_category2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        getContentPane().add(jComboBox_category2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 270, -1));

        jLabel_artname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_artname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_artname.setText("Art Name:");
        getContentPane().add(jLabel_artname, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 189, 100, -1));

        jTextField_artname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jTextField_artname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_artnameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_artname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 270, -1));

        jButton_save.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton_save.setText("Save");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 242, -1, -1));

        jButton_clear.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        jButton_clear.setText("Clear");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 242, -1, -1));

        jButton_close1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton_close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_close1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_close1, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 10, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -790, 700, 1190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_artistnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_artistnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_artistnameActionPerformed

    private void jTextField_artistnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_artistnameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jTextField_artistnameKeyReleased

    private void jTextField_artnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_artnameKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_jTextField_artnameKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while(itr.hasNext())
        {
            Category categoryobj = itr.next();
            jComboBox_category2.addItem(categoryobj.getName());
        }
        
    }//GEN-LAST:event_formComponentShown

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
        Artist artist =new Artist();
        artist.setArtist_name(jTextField_artistname.getText());
        artist.setCategory((String)jComboBox_category2.getSelectedItem());
        artist.setArt_name(jTextField_artname.getText());
        ArtistDao.save(artist);
        setVisible(false);
        new AddNewArtist1().setVisible(true);
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddNewArtist1().setVisible(true);
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_close1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton_close1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewArtist1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewArtist1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewArtist1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewArtist1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewArtist1().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_close1;
    private javax.swing.JButton jButton_save;
    private javax.swing.JComboBox<String> jComboBox_category2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_artistname;
    private javax.swing.JLabel jLabel_artname;
    private javax.swing.JLabel jLabel_category2;
    private javax.swing.JLabel jLabel_heading;
    private javax.swing.JTextField jTextField_artistname;
    private javax.swing.JTextField jTextField_artname;
    // End of variables declaration//GEN-END:variables
}
