/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package art_gallery;

import javax.swing.JOptionPane;
import model.User;
import dao.UserDao;

/**
 *
 * @author Admin
 */
public class ForgotPassword extends javax.swing.JFrame {
    
    private String dbAnswer = null;
    private String email = null;
    private String emailPatern = "^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        B_update.setEnabled(false);
        B_search.setEnabled(false);
        T_security.setEditable(false);
    }
    
    public void clear(){                            // clear btn er jonno 
        
        B_update.setEnabled(false);
        B_search.setEnabled(false);
        T_email.setEditable(true);
        T_email.setText("");
        T_security.setText("");
        T_answer.setText("");
        T_newpassword.setText("");
        
    }
    
    public void validateEmail(){
        email= T_email.getText();
        if(email.matches(emailPatern)){
            B_search.setEnabled(true);
        }
        else
            B_search.setEnabled(false);
    }
    
    
    public void validateFields(){
        String password = T_newpassword.getText();
        String answer = T_answer.getText();
        String securityQuestion = T_security.getText();
        if(!password.equals("") && !answer.equals("") && !securityQuestion.equals(""))
            B_update.setEnabled(true);
        else
            B_update.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        L_Email = new javax.swing.JLabel();
        L_Security = new javax.swing.JLabel();
        L_Answer = new javax.swing.JLabel();
        L_Newpassword = new javax.swing.JLabel();
        T_email = new javax.swing.JTextField();
        T_security = new javax.swing.JTextField();
        T_answer = new javax.swing.JTextField();
        T_newpassword = new javax.swing.JPasswordField();
        B_search = new javax.swing.JButton();
        B_update = new javax.swing.JButton();
        B_clear = new javax.swing.JButton();
        B_exit = new javax.swing.JButton();
        B_signup = new javax.swing.JButton();
        B_login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Forgot Password ?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 75, -1, -1));

        L_Email.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L_Email.setForeground(new java.awt.Color(255, 255, 255));
        L_Email.setText("Email");
        getContentPane().add(L_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        L_Security.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L_Security.setForeground(new java.awt.Color(255, 255, 255));
        L_Security.setText("Your Security Question");
        getContentPane().add(L_Security, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        L_Answer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L_Answer.setForeground(new java.awt.Color(255, 255, 255));
        L_Answer.setText("Your Answer");
        getContentPane().add(L_Answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        L_Newpassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L_Newpassword.setForeground(new java.awt.Color(255, 255, 255));
        L_Newpassword.setText("Enter New Password");
        getContentPane().add(L_Newpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, -1, -1));

        T_email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T_email.setText("dsd@gmail.com");
        T_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_emailActionPerformed(evt);
            }
        });
        T_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                T_emailKeyReleased(evt);
            }
        });
        getContentPane().add(T_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 179, 379, -1));

        T_security.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T_security.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                T_securityKeyReleased(evt);
            }
        });
        getContentPane().add(T_security, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 229, 379, -1));

        T_answer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T_answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_answerActionPerformed(evt);
            }
        });
        T_answer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                T_answerKeyReleased(evt);
            }
        });
        getContentPane().add(T_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 275, 379, -1));

        T_newpassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        T_newpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                T_newpasswordKeyReleased(evt);
            }
        });
        getContentPane().add(T_newpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 323, 379, -1));

        B_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        B_search.setText("Search");
        B_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_searchActionPerformed(evt);
            }
        });
        getContentPane().add(B_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(754, 176, -1, -1));

        B_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_update.setText("Update");
        B_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_updateActionPerformed(evt);
            }
        });
        getContentPane().add(B_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 410, -1, -1));

        B_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        B_clear.setText("Clear");
        B_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_clearActionPerformed(evt);
            }
        });
        getContentPane().add(B_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 408, -1, -1));

        B_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        B_exit.setText("Exit");
        B_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_exitActionPerformed(evt);
            }
        });
        getContentPane().add(B_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 408, -1, -1));

        B_signup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_signup.setText("Signup");
        B_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_signupActionPerformed(evt);
            }
        });
        getContentPane().add(B_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(636, 410, -1, -1));

        B_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_login.setText("Login");
        B_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_loginActionPerformed(evt);
            }
        });
        getContentPane().add(B_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginBG.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -2, 1070, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_emailActionPerformed

    private void T_answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_answerActionPerformed

    private void B_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_loginActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_B_loginActionPerformed

    private void T_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T_emailKeyReleased
        // TODO add your handling code here:
        validateEmail();
    }//GEN-LAST:event_T_emailKeyReleased

    private void T_securityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T_securityKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_T_securityKeyReleased

    private void T_answerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T_answerKeyReleased
        // TODO add your handling code here:
         validateFields();
    }//GEN-LAST:event_T_answerKeyReleased

    private void T_newpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_T_newpasswordKeyReleased
        // TODO add your handling code here:
         validateFields();
    }//GEN-LAST:event_T_newpasswordKeyReleased

    private void B_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_exitActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to close ","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_B_exitActionPerformed

    private void B_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_B_clearActionPerformed

    private void B_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_updateActionPerformed
        // TODO add your handling code here:
        String answer = T_answer.getText();
        String newPassword = T_newpassword.getText();
        if(answer.equals(dbAnswer)){
            UserDao.update(email, newPassword);
            clear();
        }
        else{
            JOptionPane.showMessageDialog(null," Incorrect Email ","Message",JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_B_updateActionPerformed

    private void B_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_searchActionPerformed
        // TODO add your handling code here:
        email= T_email.getText();
        User user = null;
        user = UserDao.getSEcurityQuestion(email);
        if(user == null){
            JOptionPane.showMessageDialog(null," Incorrect Email ","Message",JOptionPane.ERROR_MESSAGE);
            
        }
        else                          //if user in not exist
        {
            B_search.setEnabled(false);
            T_email.setEditable(false );
            dbAnswer = user.getAnswer();
            T_security.setText(user.getSecurityQuestion());
            validateFields();
            
        }
    }//GEN-LAST:event_B_searchActionPerformed

    private void B_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_signupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Signup().setVisible(true);
    }//GEN-LAST:event_B_signupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_clear;
    private javax.swing.JButton B_exit;
    private javax.swing.JButton B_login;
    private javax.swing.JButton B_search;
    private javax.swing.JButton B_signup;
    private javax.swing.JButton B_update;
    private javax.swing.JLabel L_Answer;
    private javax.swing.JLabel L_Email;
    private javax.swing.JLabel L_Newpassword;
    private javax.swing.JLabel L_Security;
    private javax.swing.JTextField T_answer;
    private javax.swing.JTextField T_email;
    private javax.swing.JPasswordField T_newpassword;
    private javax.swing.JTextField T_security;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
