/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package art_gallery;

import javax.swing.JOptionPane;

/**
 *
 * @author Ahad
 */
public class Home extends javax.swing.JFrame {
    public String email;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    public Home(String userEmail){
        initComponents();
        email= userEmail;
        if(!email.equals("admin@gmail.com"))
        {
            btnhome_managecat.setVisible(false);
            btnhome_newproduct.setVisible(false);
            btnhome_vieweditdelete.setVisible(false);
            jButton3.setVisible(false);
            jButton1.setVisible(false);
            jButton2.setVisible(false);
    }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_logout = new javax.swing.JButton();
        home_placeorder = new javax.swing.JButton();
        home_billorderdetails = new javax.swing.JButton();
        home_changepass = new javax.swing.JButton();
        home_changesecurityques = new javax.swing.JButton();
        home_exit = new javax.swing.JButton();
        btnhome_managecat = new javax.swing.JButton();
        btnhome_newproduct = new javax.swing.JButton();
        btnhome_vieweditdelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home_logout.setBackground(new java.awt.Color(255, 255, 255));
        home_logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        home_logout.setText("Logout");
        home_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(home_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        home_placeorder.setBackground(new java.awt.Color(255, 255, 255));
        home_placeorder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home_placeorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/place order.png"))); // NOI18N
        home_placeorder.setText("Place Order");
        home_placeorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_placeorderActionPerformed(evt);
            }
        });
        getContentPane().add(home_placeorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, -1, -1));

        home_billorderdetails.setBackground(new java.awt.Color(255, 255, 255));
        home_billorderdetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home_billorderdetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/View Bills & Order Placed Details.png"))); // NOI18N
        home_billorderdetails.setText("View Bill & Order Placed Details");
        home_billorderdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_billorderdetailsActionPerformed(evt);
            }
        });
//        getContentPane().add(home_billorderdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, -1));

        home_changepass.setBackground(new java.awt.Color(255, 255, 255));
        home_changepass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home_changepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Password.png"))); // NOI18N
        home_changepass.setText("Change Password");
        home_changepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_changepassActionPerformed(evt);
            }
        });
//        getContentPane().add(home_changepass, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        home_changesecurityques.setBackground(new java.awt.Color(255, 255, 255));
        home_changesecurityques.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home_changesecurityques.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/change Security Question.png"))); // NOI18N
        home_changesecurityques.setText("Change Security Question");
//        getContentPane().add(home_changesecurityques, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));

        home_exit.setBackground(new java.awt.Color(255, 255, 255));
        home_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        home_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        home_exit.setText("Exit");
        home_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_exitActionPerformed(evt);
            }
        });
        getContentPane().add(home_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));

        btnhome_managecat.setBackground(new java.awt.Color(255, 255, 255));
        btnhome_managecat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnhome_managecat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/category.png"))); // NOI18N
        btnhome_managecat.setText("Manage Category");
        btnhome_managecat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome_managecatActionPerformed(evt);
            }
        });
//        getContentPane().add(btnhome_managecat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        btnhome_newproduct.setBackground(new java.awt.Color(255, 255, 255));
        btnhome_newproduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnhome_newproduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        btnhome_newproduct.setText("New Artwork");
        btnhome_newproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome_newproductActionPerformed(evt);
            }
        });
//        getContentPane().add(btnhome_newproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        btnhome_vieweditdelete.setBackground(new java.awt.Color(255, 255, 255));
        btnhome_vieweditdelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnhome_vieweditdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        btnhome_vieweditdelete.setText("View,Edit & Delete Artwork");
        btnhome_vieweditdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhome_vieweditdeleteActionPerformed(evt);
            }
        });
//        getContentPane().add(btnhome_vieweditdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("New Artist");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
//        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, -1, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        jButton2.setText("View,Edit& Delete   Artist");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
//        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, 250, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/verify users.png"))); // NOI18N
        jButton3.setText("Verify User");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
//        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home_f.png"))); // NOI18N
        jLabel2.setText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_logoutActionPerformed
      int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout","Select",JOptionPane.YES_NO_OPTION);
      if(a==0){
          setVisible(false);
          new Login().setVisible(true);
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_home_logoutActionPerformed

    private void home_billorderdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_billorderdetailsActionPerformed
        // TODO add your handling code here:
//        new ViewBills().setVisible(true);
    }//GEN-LAST:event_home_billorderdetailsActionPerformed

    private void home_changepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_changepassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_home_changepassActionPerformed

    private void btnhome_managecatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome_managecatActionPerformed
        new ManageCategory().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnhome_managecatActionPerformed

    private void home_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_exitActionPerformed
 int a = JOptionPane.showConfirmDialog(null, "Do you really want to Close Application","Select",JOptionPane.YES_NO_OPTION);
      if(a==0){
          System.exit(0);
      }
                // TODO add your handling code here:
    }//GEN-LAST:event_home_exitActionPerformed

    private void btnhome_newproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome_newproductActionPerformed
        // TODO add your handling code here:
        new AddNewArt().setVisible(true);
    }//GEN-LAST:event_btnhome_newproductActionPerformed

    private void home_placeorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_placeorderActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PlaceOrder(email).setVisible(true);
    }//GEN-LAST:event_home_placeorderActionPerformed

    private void btnhome_vieweditdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhome_vieweditdeleteActionPerformed
        // TODO add your handling code here:
         new ViewEditDelete().setVisible(true);
        
    }//GEN-LAST:event_btnhome_vieweditdeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new AddNewArtist1().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new ViewEditDeleteArtist().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling 
       new VerifyUsers().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhome_managecat;
    private javax.swing.JButton btnhome_newproduct;
    private javax.swing.JButton btnhome_vieweditdelete;
    private javax.swing.JButton home_billorderdetails;
    private javax.swing.JButton home_changepass;
    private javax.swing.JButton home_changesecurityques;
    private javax.swing.JButton home_exit;
    private javax.swing.JButton home_logout;
    private javax.swing.JButton home_placeorder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
