/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package art_gallery;

import dao.UserDao;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.User;
import dao.tables;

import java.util.Objects;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {
   public String emailpattern =" ^ [a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        B_LOGIN.setEnabled(false);
    }
    
    public void clear(){
        EMAILID.setText("");
        PASSWORD.setText("");
        B_LOGIN.setEnabled(false);
    }
    
    public void validateFields(){
        String email = EMAILID.getText();
        String password = PASSWORD.getText();
        if(email.matches(emailpattern) && !password.equals("")){
            B_LOGIN.setEnabled(true);
         }
        else
            B_LOGIN.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T_LOGIN = new javax.swing.JLabel();
        T_EMAIL = new javax.swing.JLabel();
        T_PASSWORD = new javax.swing.JLabel();
        EMAILID = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JPasswordField();
        B_LOGIN = new javax.swing.JButton();
        B_CLEAR = new javax.swing.JButton();
        B_EXIT = new javax.swing.JButton();
        B_FORGOTPASSWORD = new javax.swing.JButton();
        B_SIGNUP = new javax.swing.JButton();
        BACKGROUNDIMAGE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        T_LOGIN.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        T_LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        T_LOGIN.setText("LOGIN");
        getContentPane().add(T_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        T_EMAIL.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T_EMAIL.setForeground(new java.awt.Color(204, 204, 204));
        T_EMAIL.setText("Email");
        getContentPane().add(T_EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 67, -1));

        T_PASSWORD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        T_PASSWORD.setForeground(new java.awt.Color(204, 204, 204));
        T_PASSWORD.setText("Password");
        getContentPane().add(T_PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        EMAILID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EMAILID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EMAILIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EMAILIDKeyReleased(evt);
            }
        });
        getContentPane().add(EMAILID, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 212, 310, -1));

        PASSWORD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PASSWORD.setText("jPasswordField1");
        PASSWORD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PASSWORDKeyReleased(evt);
            }
        });
        getContentPane().add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 253, 310, -1));

        B_LOGIN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_LOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        B_LOGIN.setText("Login");
        B_LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LOGINActionPerformed(evt);
            }
        });
        getContentPane().add(B_LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        B_CLEAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_CLEAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        B_CLEAR.setText("CLear");
        B_CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CLEARActionPerformed(evt);
            }
        });
        getContentPane().add(B_CLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        B_EXIT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_EXIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit small.png"))); // NOI18N
        B_EXIT.setText("Exit");
        B_EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EXITActionPerformed(evt);
            }
        });
        getContentPane().add(B_EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 320, -1, -1));

        B_FORGOTPASSWORD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_FORGOTPASSWORD.setText("Forgot Password?");
        B_FORGOTPASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_FORGOTPASSWORDActionPerformed(evt);
            }
        });
        getContentPane().add(B_FORGOTPASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        B_SIGNUP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        B_SIGNUP.setText("SignUP");
        B_SIGNUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SIGNUPActionPerformed(evt);
            }
        });
        getContentPane().add(B_SIGNUP, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        BACKGROUNDIMAGE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LoginBG.jpg"))); // NOI18N
        getContentPane().add(BACKGROUNDIMAGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -180, 1050, 990));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LOGINActionPerformed
        // TODO add your handling code here:
        String email = EMAILID.getText();
        String password = PASSWORD.getText();
        User user = null;
        user = UserDao.login(email, password);
        if(user==null){
            JOptionPane.showMessageDialog(null," Incorrect Username or Password ","Message",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(Objects.equals(email, "admin@gmail.com") && Objects.equals(password, "admin")){
                setVisible(false);
                new AdminDashboard().setVisible(true);
            }
            if(user.getStatus().equals("false")){
                ImageIcon icon = new ImageIcon("C:\\Users\\fdipt\\IdeaProjects\\Art_Gallery\\Art_Gallery\\src\\popupicon\\wait.png");
                JOptionPane.showMessageDialog(null," Wait for Admin Approval ","Message",JOptionPane.INFORMATION_MESSAGE,icon);
                clear();
            }
            
            if(user.getStatus().equals("true")){
                setVisible(false);
                new Home(email).setVisible(true);
            }                     
        }
    }//GEN-LAST:event_B_LOGINActionPerformed

    private void B_EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EXITActionPerformed
        // TODO add your handling code here:               
        int a = JOptionPane.showConfirmDialog(null,"do you really want to close it","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_B_EXITActionPerformed

    private void EMAILIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EMAILIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMAILIDKeyPressed

    private void EMAILIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EMAILIDKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_EMAILIDKeyReleased

    private void PASSWORDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PASSWORDKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_PASSWORDKeyReleased

    private void B_CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CLEARActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_B_CLEARActionPerformed

    private void B_SIGNUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SIGNUPActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Signup().setVisible(true);
    }//GEN-LAST:event_B_SIGNUPActionPerformed

    private void B_FORGOTPASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_FORGOTPASSWORDActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new ForgotPassword().setVisible(true);
    }//GEN-LAST:event_B_FORGOTPASSWORDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUNDIMAGE;
    private javax.swing.JButton B_CLEAR;
    private javax.swing.JButton B_EXIT;
    private javax.swing.JButton B_FORGOTPASSWORD;
    private javax.swing.JButton B_LOGIN;
    private javax.swing.JButton B_SIGNUP;
    private javax.swing.JTextField EMAILID;
    private javax.swing.JPasswordField PASSWORD;
    private javax.swing.JLabel T_EMAIL;
    private javax.swing.JLabel T_LOGIN;
    private javax.swing.JLabel T_PASSWORD;
    // End of variables declaration//GEN-END:variables
}
