/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package art_gallery;
import model.Artwork;
import dao.ArtworkDao;
import dao.CategoryDao;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Category;
/**
 *
 * @author Admin
 */
public class ViewEditDelete extends javax.swing.JFrame {

    /**
     * Creates new form ViewEditDelete
     */
    public ViewEditDelete() {
        initComponents();
        jButton_update.setEnabled(false);
        jButton_delete.setEnabled(false);
    }
    
    
    public void validateField(){
        String name = jTextField_name.getText();
        String price = jTextField_price.getText();
        String category = (String) jComboBox_category.getSelectedItem();
        if(!name.equals("")&& !price.equals("")&& category != null)
           jButton_update.setEnabled(true);
        else
            jButton_update.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_header = new javax.swing.JLabel();
        jButton_close = new javax.swing.JButton();
        jLabel_id = new javax.swing.JLabel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_category = new javax.swing.JLabel();
        jLabel_price = new javax.swing.JLabel();
        jLabel_id_answer = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jComboBox_category = new javax.swing.JComboBox<>();
        jTextField_price = new javax.swing.JTextField();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_header.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_header.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_header.setText("View ,Edit,Delete painting");
        getContentPane().add(jLabel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 0, 298, 46));

        jButton_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_closeActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, 40, -1));

        jLabel_id.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_id.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_id.setText("ID:");
        getContentPane().add(jLabel_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, 20));

        jLabel_name.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name.setText("Art Name:");
        getContentPane().add(jLabel_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, 20));

        jLabel_category.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_category.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_category.setText("Category:");
        getContentPane().add(jLabel_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, 20));

        jLabel_price.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_price.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_price.setText("Price:");
        getContentPane().add(jLabel_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, 20));

        jLabel_id_answer.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel_id_answer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_id_answer.setText("00");
        getContentPane().add(jLabel_id_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, 20));

        jTextField_name.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 380, 30));

        jComboBox_category.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jComboBox_category.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBox_categoryKeyReleased(evt);
            }
        });
        getContentPane().add(jComboBox_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 389, 30));

        jTextField_price.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jTextField_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_priceKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 389, 30));

        jButton_update.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 120, 30));

        jButton_delete.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, 30));

        jButton_clear.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButton_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        jButton_clear.setText("Clear");
        getContentPane().add(jButton_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, 30));

        jTable1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 440, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        Artwork  artwork = new Artwork();
        int id = Integer.parseInt(jLabel_id_answer.getText());
        artwork.setId(id);
        artwork.setName(jTextField_name.getText());
        artwork.setCategory((String)jComboBox_category.getSelectedItem());
        artwork.setPrice(jTextField_price.getText());
        ArtworkDao.update(artwork);
        setVisible(false);
        new ViewEditDelete().setVisible(true);
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jTextField_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nameKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_jTextField_nameKeyReleased

    private void jComboBox_categoryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox_categoryKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_categoryKeyReleased

    private void jTextField_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_priceKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_jTextField_priceKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Artwork> list = ArtworkDao.getAllRecords();
        Iterator<Artwork> itr = list.iterator();
        while(itr.hasNext()){
            Artwork artworkObj = itr.next();
            dtm.addRow(new Object[]{artworkObj.getId(),artworkObj.getName(),artworkObj.getCategory(),artworkObj.getPrice()});
            
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(index, 0).toString();
        jLabel_id_answer.setText(id);
        String name =model.getValueAt(index,1).toString();
        jTextField_name.setText(name);
        String category = model.getValueAt(index, 2).toString();
        String price = model.getValueAt(index,3).toString();
        jTextField_price.setText(price);
        
        jButton_update.setEnabled(true);
        jButton_delete.setEnabled(true);
        
        jComboBox_category.removeAllItems();
        jComboBox_category.addItem(category);
        ArrayList<Category> categoryList = CategoryDao.getAllRecords();
        Iterator<Category> categoryItr = categoryList.iterator();
        while(categoryItr.hasNext()){
            Category categoryObj = categoryItr.next();
            if(!categoryObj.getName().equals(category)){
               jComboBox_category.addItem(categoryObj.getName());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        String id = jLabel_id_answer.getText();
        int a = JOptionPane.showConfirmDialog(null,"Do you want to delete this artwork","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            ArtworkDao.delete(id);
            setVisible(false);
            new ViewEditDelete().setVisible(true);
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_closeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_close;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox<String> jComboBox_category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_category;
    private javax.swing.JLabel jLabel_header;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JLabel jLabel_id_answer;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_price;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_price;
    // End of variables declaration//GEN-END:variables
}
