/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package art_gallery;


import dao.ArtistDao;
import dao.CategoryDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Artist;
import model.Category;


/**
 *
 * @author Admin
 */
public class ViewEditDeleteArtist extends javax.swing.JFrame {

    /** Creates new form ViewEditDeleteArtist */
    public ViewEditDeleteArtist() {
        initComponents();
        jButton_update.setEnabled(false);
        jButton_delete.setEnabled(false);
    }
    
     
    public void validateField(){
        String artist_name = jTextField_artistname.getText();
        String art_name = jTextField_artname.getText();
        String category = (String) jComboBox_category.getSelectedItem();
        if(!artist_name.equals("")&& !art_name.equals("")&& category != null)
           jButton_update.setEnabled(true);
        else
            jButton_update.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_idartist = new javax.swing.JLabel();
        jLabel_artistname = new javax.swing.JLabel();
        jLabel_Category = new javax.swing.JLabel();
        jLabel_artname = new javax.swing.JLabel();
        jLabel_idanswer = new javax.swing.JLabel();
        jTextField_artistname = new javax.swing.JTextField();
        jTextField_artname = new javax.swing.JTextField();
        jComboBox_category = new javax.swing.JComboBox<>();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View,Edit,Delete of Artist");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 268, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1003, 0, 43, 40));

        jLabel_idartist.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_idartist.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_idartist.setText("ID:");
        getContentPane().add(jLabel_idartist, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 151, -1, -1));

        jLabel_artistname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_artistname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_artistname.setText("Artist Name:");
        getContentPane().add(jLabel_artistname, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 206, -1, -1));

        jLabel_Category.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_Category.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Category.setText("Category:");
        getContentPane().add(jLabel_Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 262, -1, -1));

        jLabel_artname.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel_artname.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_artname.setText("Art Name:");
        getContentPane().add(jLabel_artname, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 335, -1, -1));

        jLabel_idanswer.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel_idanswer.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_idanswer.setText("00");
        getContentPane().add(jLabel_idanswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 151, -1, -1));

        jTextField_artistname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextField_artistname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_artistnameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_artistname, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 203, 362, -1));

        jTextField_artname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jTextField_artname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_artnameKeyReleased(evt);
            }
        });
        getContentPane().add(jTextField_artname, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 332, 362, -1));

        jComboBox_category.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        getContentPane().add(jComboBox_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 259, 362, -1));

        jButton_update.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 385, -1, -1));

        jButton_delete.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 385, -1, -1));

        jButton_clear.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        jButton_clear.setText("Clear");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 385, -1, -1));

        jTable1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Artist Name", "Category", "Art Name"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG.png"))); // NOI18N
        jLabel2.setText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-870, -370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_artistnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_artistnameKeyReleased
        // TODO add your handling code here:
         validateField();
    }//GEN-LAST:event_jTextField_artistnameKeyReleased

    private void jTextField_artnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_artnameKeyReleased
        // TODO add your handling code here:
         validateField();
    }//GEN-LAST:event_jTextField_artnameKeyReleased

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
         Artist  artist = new Artist();
        int id = Integer.parseInt(jLabel_idanswer.getText());
        artist.setId(id);
        artist.setArtist_name(jTextField_artistname.getText());
        artist.setCategory((String)jComboBox_category.getSelectedItem());
        artist.setArt_name(jTextField_artname.getText());
        ArtistDao.update(artist);
        setVisible(false);
        new ViewEditDelete().setVisible(true);
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
         DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Artist> list = ArtistDao.getAllRecords();
        Iterator<Artist> itr = list.iterator();
        while(itr.hasNext()){
            Artist artistObj = itr.next();
            dtm.addRow(new Object[]{artistObj.getId(),artistObj.getArtist_name(),artistObj.getCategory(),artistObj.getArt_name()});
            
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(index, 0).toString();
        jLabel_idanswer.setText(id);
        String artist_name =model.getValueAt(index,1).toString();
        jTextField_artistname.setText(artist_name);
        String category = model.getValueAt(index, 2).toString();
        String art_name = model.getValueAt(index,3).toString();
        jTextField_artname.setText(art_name);
        
        jButton_update.setEnabled(true);
        jButton_delete.setEnabled(true);
        
        jComboBox_category.removeAllItems();
        jComboBox_category.addItem(category);
        ArrayList<Category> categoryList = CategoryDao.getAllRecords();
        Iterator<Category> categoryItr = categoryList.iterator();
        while(categoryItr.hasNext()){
            Category categoryObj1 = categoryItr.next();
            if(!categoryObj1.getName().equals(category)){
               jComboBox_category.addItem(categoryObj1.getName());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        String id = jLabel_idanswer.getText();
        int a = JOptionPane.showConfirmDialog(null,"Do you want to delete this artist & his art?","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            ArtistDao.delete(id);
            setVisible(false);
            new ViewEditDelete().setVisible(true);
        }
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
        // TODO add your handling code here:
         setVisible(false);
            new ViewEditDelete().setVisible(true);
        
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteArtist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditDeleteArtist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox<String> jComboBox_category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Category;
    private javax.swing.JLabel jLabel_artistname;
    private javax.swing.JLabel jLabel_artname;
    private javax.swing.JLabel jLabel_idanswer;
    private javax.swing.JLabel jLabel_idartist;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_artistname;
    private javax.swing.JTextField jTextField_artname;
    // End of variables declaration//GEN-END:variables

}
